FROM golang:1.22 as builder
WORKDIR /app
COPY . .
COPY . /app
RUN mkdir -p /app/logs && touch /app/logs/app.log
RUN GO111MODULE=auto CGO_ENABLED=0 GOOS=linux GOPROXY=https://proxy.golang.org go build -o app cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app .
COPY --from=builder /app/logs .
COPY --from=builder /app/internal/config .

ENTRYPOINT ["./app"]
